### ISSUE TITLE
Got panic If i give wrong repository name.

### ISSUE THREAD

**Issue by anisurrahman75** [luisedmc/ghcmd#2]
- In searching the repo section. When i provide  wrong repo-name 
-  I got panic.
- `go Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /home/anisur/go/src/github.com/luisedmc/ghcmd/vendor/github.com/charmbracelet/bubbletea/tea.go:440 +0x95
panic({0x7573a0, 0xaa8450})
        /usr/local/go/src/runtime/panic.go:890 +0x263
main.SearchRepository({0x850d78?, 0xc00002e0e8?}, 0x9?, {0xc000258960?, 0x5?}, {0xc000487c40?, 0x4?})
        /home/anisur/go/src/github.com/luisedmc/ghcmd/services.go:42 +0xd7
main.Model.Update({0xf, {0x0, 0x0, {0x7bcf4a, 0x5}, {0x7bcbbf, 0x4}, {0x7bcba7, 0x3}, {{0xab4f30, ...}, ...}}, ...}, ...)
        /home/anisur/go/src/github.com/luisedmc/ghcmd/tui.go:188 +0x638
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc000000000, {0x850c50?, 0xc00063d500?}, 0x10?)
        /home/anisur/go/src/github.com/luisedmc/ghcmd/vendor/github.com/charmbracelet/bubbletea/tea.go:373 +0x646
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000000000)
        /home/anisur/go/src/github.com/luisedmc/ghcmd/vendor/github.com/charmbracelet/bubbletea/tea.go:503 +0x87d
main.main()
        /home/anisur/go/src/github.com/luisedmc/ghcmd/main.go:12 +0x8a`

**Comment by luisedmc** [comment]
Hi @anisurrahman75, I just tested searching for:
- wrong name only
- wrong repo name only
- both name and repo name wrong
My results are the default error message saying: Repository not found! The repository searched was not found!                                                                                                                                                             
I tested on the release version and the latest code from master branch on github.
Which version (1.0.0 or latest) are you using ?

**Comment by anisurrahman75** [comment]
``
func SearchRepository(ctx context.Context, githubClient *github.Client, user string, repositoryName string) *Repository {
	......
	if *repository.Private {
		return nil
	}
	if checkRepoNilOrNot(repository) {
		return nil
	}
	.....
	return repositoryData
}

``


``
func checkRepoNilOrNot(repository *github.Repository) bool {
	return repository.Owner.Login == nil || repository.Owner.HTMLURL == nil || repository.Description == nil || repository.HTMLURL == nil
}
``

**Comment by anisurrahman75** [comment]
Just add above code, it will resolve this.

**Comment by anisurrahman75** [comment]
- My bad it's not for the wrong repository
- I think it's for my GitHub Account API Token permission issues.
- but the above condition fix this issue.

**Comment by luisedmc** [comment]
@anisurrahman75 you're right. I tested searching for a repo without description for example and got the same error as you. Thanks for the code you provided, I modified a little bit to solve this issues.
I just didn't use your entire code because If only the description is nil I still want to return the rest of the information (url, name). Thanks for the help.

**Comment by anisurrahman75** [comment]
- Welcome, You are doing great stuff. I also code Golang.
- I want to contribute to any Golang-related project. Have you any.! let me know..?

**Comment by luisedmc** [comment]
> * Welcome, You are doing great stuff. I also code Golang.
> * I want to contribute to any Golang-related project. Have you any.! let me know..?

Nice, Go is the way, keep it going.
I think the only interesting Go project that I have is ghcmd 😅, feel free to come back whenever u want.
